# messaging/events.py

ML_EVENTS_QUEUE = "ml.events"

JOB_STARTED                 = "JOB_STARTED"

JD_PARSING_STARTED          = "JD_PARSING_STARTED"
JD_PARSING_COMPLETED        = "JD_PARSING_COMPLETED"

RESUMES_PARSING_STARTED     = "RESUMES_PARSING_STARTED"
RESUME_PARSING_STARTED      = "RESUME_PARSING_STARTED"
RESUME_PARSING_COMPLETED    = "RESUME_PARSING_COMPLETED"
RESUMES_PARSING_COMPLETED   = "RESUMES_PARSING_COMPLETED"

RESUMES_MATCHING_STARTED    = "RESUMES_MATCHING_STARTED"
RESUME_MATCHING_STARTED     = "RESUME_MATCHING_STARTED"      # ← was missing
RESUME_MATCHING_COMPLETED   = "RESUME_MATCHING_COMPLETED"
RESUMES_MATCHING_COMPLETED  = "RESUMES_MATCHING_COMPLETED"

RESUMES_RANKING_STARTED    = "RESUMES_RANKING_STARTED"   # ← NEW
RESUMES_RANKING_COMPLETED  = "RESUMES_RANKING_COMPLETED" # ← NEW

JOB_COMPLETED               = "JOB_COMPLETED"
JOB_FAILED                  = "JOB_FAILED"

